### ISSUE TITLE
Archlinux segfault

### ISSUE THREAD

**Issue by blueblob** [KenjiTakahashi/pacmixer#13]
I get a segfault on archlinux on two different machines both when I install from the AUR:

```
pacman -Qi pacmixer
Name           : pacmixer
Version        : 0.6.2-2
...
```

Or when I build from source. I am not sure whether I am missing a dependency because I have had some sort of issue since the pulseaudio split. The error only occurs when I have a program running such as `pianobar` or `skype` both of which were installed from the `community`.

My backtrace:
```
(gdb) bt     │  │     │  │
#0  0x00007ffff61690ca in strlen () from /usr/lib/libc.so.6
#1  0x00007ffff78dcbc6 in ?? () from /usr/lib/libgnustep-base.so.1.24
#2  0x00007ffff78da417 in ?? () from /usr/lib/libgnustep-base.so.1.24
#3  0x000000000042005e in callback_add_func (self_=0x7c5ed0, 
    name=0x7fffe4027260 "libao[pianobar]", type=<optimized out>, idx=47, 
    data=0x7fffeabfdac0) at src/middleware.m:110
#4  0x0000000000407ddc in _cb_client (c=0x7c68e0, info=0x7fffeabfdb20, eol=0, 
    userdata=0x7fffe400dbc0) at src/backend.c:209
#5  0x00007ffff69ba813 in ?? () from /usr/lib/libpulse.so.0
#6  0x00007ffff415c801 in ?? () from /usr/lib/pulseaudio/libpulsecommon-7.1.so
#7  0x00007ffff415cb8b in pa_pdispatch_run ()
   from /usr/lib/pulseaudio/libpulsecommon-7.1.so
#8  0x00007ffff69b072e in ?? () from /usr/lib/libpulse.so.0
#9  0x00007ffff415f3ff in ?? () from /usr/lib/pulseaudio/libpulsecommon-7.1.so
#10 0x00007ffff4161a5b in ?? () from /usr/lib/pulseaudio/libpulsecommon-7.1.so
#11 0x00007ffff4161e09 in ?? () from /usr/lib/pulseaudio/libpulsecommon-7.1.so
#12 0x00007ffff416269a in ?? () from /usr/lib/pulseaudio/libpulsecommon-7.1.so
#13 0x00007ffff69c5817 in pa_mainloop_dispatch () from /usr/lib/libpulse.so.0
#14 0x00007ffff69c5c1c in pa_mainloop_iterate () from /usr/lib/libpulse.so.0
#15 0x00007ffff69c5cc0 in pa_mainloop_run () from /usr/lib/libpulse.so.0
#16 0x00007ffff69d3ee6 in ?? () from /usr/lib/libpulse.so.0
#17 0x00007ffff41725f8 in ?? () from /usr/lib/pulseaudio/libpulsecommon-7.1.so
#18 0x00007ffff4bb84a4 in start_thread () from /usr/lib/libpthread.so.0
#19 0x00007ffff61d113d in clone () from /usr/lib/libc.so.6
```

**Comment by blueblob** [comment]
```
cat .local/share/pacmixer/pacmixer.log 
[2015-11-11 18:01:23](src/backend.c:175):B:server state changed to 1
[2015-11-11 18:01:23](src/backend.c:175):B:server state changed to 2
[2015-11-11 18:01:23](src/backend.c:175):B:server state changed to 3
[2015-11-11 18:01:23](src/backend.c:175):B:server state changed to 4
[2015-11-11 18:01:23](src/middleware.m:89):M:volumeChanged0_0_0 observer added
[2015-11-11 18:01:23](src/middleware.m:89):M:volumeChanged0_0_1 observer added
[2015-11-11 18:01:23](src/middleware.m:100):M:muteChanged0_0 observer added
[2015-11-11 18:01:23](src/middleware.m:101):M:0:GF119 HDMI Audio Controller Digital Stereo (HDMI) received
[2015-11-11 18:01:23](src/main.mm:83):D:0:GF119 HDMI Audio Controller Digital Stereo (HDMI) passed
[2015-11-11 18:01:23](src/widgets/widget.mm:43):F:0:GF119 HDMI Audio Controller Digital Stereo (HDMI) posted
[2015-11-11 18:01:23](src/widgets/widget.mm:159):F:0:GF119 HDMI Audio Controller Digital Stereo (HDMI) options added
[2015-11-11 18:01:23](src/middleware.m:141):M:volumeChanged0_0 observer added
[2015-11-11 18:01:23](src/middleware.m:89):M:volumeChanged1_0_0 observer added
[2015-11-11 18:01:23](src/middleware.m:89):M:volumeChanged1_0_1 observer added
[2015-11-11 18:01:23](src/middleware.m:100):M:muteChanged1_0 observer added
[2015-11-11 18:01:23](src/middleware.m:101):M:1:Built-in Audio Analog Stereo received
[2015-11-11 18:01:23](src/main.mm:83):D:1:Built-in Audio Analog Stereo passed
[2015-11-11 18:01:23](src/widgets/widget.mm:43):F:1:Built-in Audio Analog Stereo posted
[2015-11-11 18:01:23](src/widgets/widget.mm:159):F:1:Built-in Audio Analog Stereo options added
[2015-11-11 18:01:23](src/middleware.m:141):M:volumeChanged1_0 observer added
[2015-11-11 18:01:23](src/middleware.m:89):M:volumeChanged0_2_0 observer added
[2015-11-11 18:01:23](src/middleware.m:89):M:volumeChanged0_2_1 observer added
[2015-11-11 18:01:23](src/middleware.m:100):M:muteChanged0_2 observer added
[2015-11-11 18:01:23](src/middleware.m:101):M:0:Monitor of GF119 HDMI Audio Controller Digital Stereo (HDMI) received
[2015-11-11 18:01:23](src/main.mm:83):D:0:Monitor of GF119 HDMI Audio Controller Digital Stereo (HDMI) passed
[2015-11-11 18:01:23](src/widgets/widget.mm:43):F:0:Monitor of GF119 HDMI Audio Controller Digital Stereo (HDMI) posted
[2015-11-11 18:01:23](src/middleware.m:141):M:volumeChanged0_2 observer added
[2015-11-11 18:01:23](src/middleware.m:89):M:volumeChanged1_2_0 observer added
[2015-11-11 18:01:23](src/middleware.m:89):M:volumeChanged1_2_1 observer added
[2015-11-11 18:01:23](src/middleware.m:100):M:muteChanged1_2 observer added
[2015-11-11 18:01:23](src/middleware.m:101):M:1:Monitor of Built-in Audio Analog Stereo received
[2015-11-11 18:01:23](src/main.mm:83):D:1:Monitor of Built-in Audio Analog Stereo passed
[2015-11-11 18:01:23](src/widgets/widget.mm:43):F:1:Monitor of Built-in Audio Analog Stereo posted
[2015-11-11 18:01:23](src/middleware.m:141):M:volumeChanged1_2 observer added
[2015-11-11 18:01:23](src/middleware.m:89):M:volumeChanged2_2_0 observer added
[2015-11-11 18:01:23](src/middleware.m:89):M:volumeChanged2_2_1 observer added
[2015-11-11 18:01:23](src/middleware.m:100):M:muteChanged2_2 observer added
[2015-11-11 18:01:23](src/middleware.m:101):M:2:Built-in Audio Analog Stereo received
[2015-11-11 18:01:23](src/main.mm:83):D:2:Built-in Audio Analog Stereo passed
[2015-11-11 18:01:23](src/widgets/widget.mm:43):F:2:Built-in Audio Analog Stereo posted
[2015-11-11 18:01:23](src/widgets/widget.mm:159):F:2:Built-in Audio Analog Stereo options added
[2015-11-11 18:01:23](src/middleware.m:141):M:volumeChanged2_2 observer added
[2015-11-11 18:01:23](src/main.mm:83):D:0:GF119 HDMI Audio Controller passed
[2015-11-11 18:01:23](src/middleware.m:141):M:activeOptionChanged0_4 observer added
[2015-11-11 18:01:23](src/main.mm:83):D:1:Built-in Audio passed
[2015-11-11 18:01:23](src/middleware.m:141):M:activeOptionChanged1_4 observer added
[2015-11-11 18:01:23](src/widgets/widget.mm:211):F:0:GF119 HDMI Audio Controller Digital Stereo (HDMI) set as default
[2015-11-11 18:01:23](src/widgets/widget.mm:211):F:1:Built-in Audio Analog Stereo set as default
[2015-11-11 18:01:23](src/widgets/widget.mm:211):F:0:Monitor of GF119 HDMI Audio Controller Digital Stereo (HDMI) set as default
[2015-11-11 18:01:23](src/widgets/widget.mm:211):F:1:Monitor of Built-in Audio Analog Stereo set as default
[2015-11-11 18:01:23](src/widgets/widget.mm:211):F:2:Built-in Audio Analog Stereo set as default
[2015-11-11 18:01:23](src/backend.c:202):B:1455:libao[pianobar] appeared
[2015-11-11 18:01:23](src/middleware.m:89):M:volumeChanged1455_1_0 observer added
[2015-11-11 18:01:23](src/middleware.m:89):M:volumeChanged1455_1_1 observer added
[2015-11-11 18:01:23](src/middleware.m:100):M:muteChanged1455_1 observer added
[2015-11-11 18:01:23](src/middleware.m:101):M:1455:libao[pianobar] received
```

**Comment by blueblob** [comment]
```
./pacmixer_run_tests 
===============================================================================
All tests passed (318 assertions in 30 test cases)
```

**Comment by KenjiTakahashi** [comment]
Hi, thanks for the detailed report! It apparently reproduces for me as well (with Skype). I think that sth's changed in PA 7 as AFAIR it worked before. Will try to investigate it ASAP.

**Comment by KenjiTakahashi** [comment]
Should be fixed on master. Can you confirm @blueblob?

**Comment by blueblob** [comment]
Indeed, it's fixed for me. Thanks!
